services:
  frontend:
    image: node:20-alpine
    container_name: port-frontend
    working_dir: /var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5180"
    ports:
      - "5180:5180"
    volumes:
      - ./frontend:/var/www
      - frontend_node_modules_data:/var/www/node_modules

volumes:
  frontend_node_modules_data:
